### ISSUE TITLE
How to use this lib? 

### ISSUE THREAD

**Issue by OZZlE** [gtsop/babel-jest-boost#6]
Our jest.config.ts:

    import type { Config } from "jest";

    // Add any custom config to be passed to Jest
    const config: Config = {
      preset: "ts-jest",
      testEnvironment: "jest-environment-jsdom",
      transform: {
        "^.+\\.(js|jsx|ts|tsx)$": "ts-jest",
      },
      coverageProvider: "v8",
      collectCoverage: true,
      roots: ["./src"],
      testTimeout: 20000,
      moduleDirectories: ["node_modules", "src"],
      moduleNameMapper: {
        "^~(.*)$": "<rootDir>/src/$1",
      },
      collectCoverageFrom: ["./src/**/*.ts", "./src/**/*.tsx"],
      coveragePathIgnorePatterns: [".*types.*", ".*d.ts", "main.tsx"],
      setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
    };
    export default config;

You seem to STILL be using require for some reason?

I tried this without luck:

    // import type { Config } from "jest";
    import { jestConfig } from "@gtsopanoglou/babel-jest-boost/config";
    const babelJestBoostPluginPath = import('@gtsopanoglou/babel-jest-boost/plugin');

    // Add any custom config to be passed to Jest
    const config: typeof jestConfig = {
      modulePaths: [],
      preset: "ts-jest",
      testEnvironment: "jest-environment-jsdom",
      transform: {
        "^.+\\.(js|jsx|ts|tsx)$": "ts-jest",
      },
      coverageProvider: "v8",
      collectCoverage: true,
      roots: ["./src"],
      testTimeout: 20000,
      moduleDirectories: ["node_modules", "src"],
      moduleNameMapper: {
        "^~(.*)$": "<rootDir>/src/$1",
      },
      collectCoverageFrom: ["./src/**/*.ts", "./src/**/*.tsx"],
      coveragePathIgnorePatterns: [".*types.*", ".*d.ts", "main.tsx"],
      setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
      plugins: [
        [
          babelJestBoostPluginPath,
          { jestConfig, /* babel-jest-boost options */ }
        ]
      ]
    };
    export default config;

**Comment by gtsop-d** [comment]
Hello @OZZlE , this library assumes you have a transformer file setup. You are correct that the instructions should be enhanced to help users without such a file. Here is a walk through:

1. This plugin works on top of `babel-jest` (thus the name `babel-jest-boost`). 

If you take a look at the babel-jest configuration you will see that you need to add a "transform" key to your `jest.config.js`
https://www.npmjs.com/package/babel-jest 

```
"transform": {
  "\\.[jt]sx?$": "babel-jest"
},
```

This tells jest to use `babel-jest` to transpile the javascript.

2. Since many people use extra configuration on this step, it is common to declare a custom file to handle this logic

For instance:

```
"transform": {
  "\\.[jt]sx?$": "<rootDir>/config/jest/babelTransform.js"
}
```

And the contents of `babelTransform.js` can be:

```
const { jestConfig } = require('@gtsopanoglou/babel-jest-boost/config');
const babelJest = require('babel-jest').default;

module.exports = babelJest.createTransformer({
  plugins: [
    [
      require.resolve('@gtsopanoglou/babel-jest-boost'),
      {
        jestConfig,
        importIgnorePatterns: [

        ],
      },
    ],
  ],
  babelrc: false,
  configFile: false,
});
```

**Comment by gtsop-d** [comment]
I will have a look into changing the default export of this plugin such that you can use a simple:

``` 
"transform": {
  "\\.[jt]sx?$": "babel-jest-boost"
},
``` 

However i expect most people to need to add some ignore patterns, so it probably won't be heavily used. It will be a good step towards initial integration though.

**Comment by gtsop** [comment]
The README has been updated to better reflect the usage of this plugin as laid out above. In the case of `ts-jest` you would have to add the `@gtsopanoglou/babel-jest-boost/plugin` plugin
